apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: pmwsl93v7-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:131ea2c728b3092e2aeb7f9cee19428886eef513@sha256:12cebdc2b71f3886594473164e0432fd1413648b7993b323d8e3a2ba56a2ff15
          name: container-image
