apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pmwsl93v7-python
  janus-idp.io/tekton: pmwsl93v7-python
  backstage.io/kubernetes-id: pmwsl93v7-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pmwsl93v7-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
